// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: proto/maps/maps.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Maps_SetGateway_FullMethodName         = "/maps.v1.Maps/SetGateway"
	Maps_SetAgents_FullMethodName          = "/maps.v1.Maps/SetAgents"
	Maps_GetRegionalGateway_FullMethodName = "/maps.v1.Maps/GetRegionalGateway"
	Maps_GetProxyGateway_FullMethodName    = "/maps.v1.Maps/GetProxyGateway"
)

// MapsClient is the client API for Maps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// protoc --go_out=. --go-grpc_out=../. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative proto/maps/maps.proto
type MapsClient interface {
	SetGateway(ctx context.Context, in *GatewayPutRequest, opts ...grpc.CallOption) (*GatewayResponse, error)
	SetAgents(ctx context.Context, in *AgentConnectionRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	GetRegionalGateway(ctx context.Context, in *GatewayHandshak, opts ...grpc.CallOption) (*GatewayResponse, error)
	GetProxyGateway(ctx context.Context, in *GatewayProxy, opts ...grpc.CallOption) (*GatewayResponse, error)
}

type mapsClient struct {
	cc grpc.ClientConnInterface
}

func NewMapsClient(cc grpc.ClientConnInterface) MapsClient {
	return &mapsClient{cc}
}

func (c *mapsClient) SetGateway(ctx context.Context, in *GatewayPutRequest, opts ...grpc.CallOption) (*GatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayResponse)
	err := c.cc.Invoke(ctx, Maps_SetGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) SetAgents(ctx context.Context, in *AgentConnectionRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, Maps_SetAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetRegionalGateway(ctx context.Context, in *GatewayHandshak, opts ...grpc.CallOption) (*GatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayResponse)
	err := c.cc.Invoke(ctx, Maps_GetRegionalGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetProxyGateway(ctx context.Context, in *GatewayProxy, opts ...grpc.CallOption) (*GatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayResponse)
	err := c.cc.Invoke(ctx, Maps_GetProxyGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapsServer is the server API for Maps service.
// All implementations must embed UnimplementedMapsServer
// for forward compatibility.
//
// protoc --go_out=. --go-grpc_out=../. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative proto/maps/maps.proto
type MapsServer interface {
	SetGateway(context.Context, *GatewayPutRequest) (*GatewayResponse, error)
	SetAgents(context.Context, *AgentConnectionRequest) (*AgentResponse, error)
	GetRegionalGateway(context.Context, *GatewayHandshak) (*GatewayResponse, error)
	GetProxyGateway(context.Context, *GatewayProxy) (*GatewayResponse, error)
	mustEmbedUnimplementedMapsServer()
}

// UnimplementedMapsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapsServer struct{}

func (UnimplementedMapsServer) SetGateway(context.Context, *GatewayPutRequest) (*GatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGateway not implemented")
}
func (UnimplementedMapsServer) SetAgents(context.Context, *AgentConnectionRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAgents not implemented")
}
func (UnimplementedMapsServer) GetRegionalGateway(context.Context, *GatewayHandshak) (*GatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegionalGateway not implemented")
}
func (UnimplementedMapsServer) GetProxyGateway(context.Context, *GatewayProxy) (*GatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProxyGateway not implemented")
}
func (UnimplementedMapsServer) mustEmbedUnimplementedMapsServer() {}
func (UnimplementedMapsServer) testEmbeddedByValue()              {}

// UnsafeMapsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapsServer will
// result in compilation errors.
type UnsafeMapsServer interface {
	mustEmbedUnimplementedMapsServer()
}

func RegisterMapsServer(s grpc.ServiceRegistrar, srv MapsServer) {
	// If the following call pancis, it indicates UnimplementedMapsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maps_ServiceDesc, srv)
}

func _Maps_SetGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).SetGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_SetGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).SetGateway(ctx, req.(*GatewayPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_SetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).SetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_SetAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).SetAgents(ctx, req.(*AgentConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetRegionalGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayHandshak)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetRegionalGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_GetRegionalGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetRegionalGateway(ctx, req.(*GatewayHandshak))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetProxyGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayProxy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetProxyGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_GetProxyGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetProxyGateway(ctx, req.(*GatewayProxy))
	}
	return interceptor(ctx, in, info, handler)
}

// Maps_ServiceDesc is the grpc.ServiceDesc for Maps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maps.v1.Maps",
	HandlerType: (*MapsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetGateway",
			Handler:    _Maps_SetGateway_Handler,
		},
		{
			MethodName: "SetAgents",
			Handler:    _Maps_SetAgents_Handler,
		},
		{
			MethodName: "GetRegionalGateway",
			Handler:    _Maps_GetRegionalGateway_Handler,
		},
		{
			MethodName: "GetProxyGateway",
			Handler:    _Maps_GetProxyGateway_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/maps/maps.proto",
}
