// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: proto/maps/maps.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentDomain   string                 `protobuf:"bytes,3,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Port          int64                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Ttl           int64                  `protobuf:"varint,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	GatewayDomain string                 `protobuf:"bytes,8,opt,name=gateway_domain,json=gatewayDomain,proto3" json:"gateway_domain,omitempty"`
	GatewayId     string                 `protobuf:"bytes,9,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,10,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistry) Reset() {
	*x = AgentRegistry{}
	mi := &file_proto_maps_maps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistry) ProtoMessage() {}

func (x *AgentRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_maps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistry.ProtoReflect.Descriptor instead.
func (*AgentRegistry) Descriptor() ([]byte, []int) {
	return file_proto_maps_maps_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegistry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistry) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentRegistry) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentRegistry) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentRegistry) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AgentRegistry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentRegistry) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *AgentRegistry) GetGatewayDomain() string {
	if x != nil {
		return x.GatewayDomain
	}
	return ""
}

func (x *AgentRegistry) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AgentRegistry) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

type GatewayRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	GatewayName   string                 `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	GatewayDomain string                 `protobuf:"bytes,3,opt,name=gateway_domain,json=gatewayDomain,proto3" json:"gateway_domain,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,4,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Ttl           int64                  `protobuf:"varint,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRegistry) Reset() {
	*x = GatewayRegistry{}
	mi := &file_proto_maps_maps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRegistry) ProtoMessage() {}

func (x *GatewayRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_maps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRegistry.ProtoReflect.Descriptor instead.
func (*GatewayRegistry) Descriptor() ([]byte, []int) {
	return file_proto_maps_maps_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayRegistry) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayRegistry) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *GatewayRegistry) GetGatewayDomain() string {
	if x != nil {
		return x.GatewayDomain
	}
	return ""
}

func (x *GatewayRegistry) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *GatewayRegistry) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GatewayRegistry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GatewayRegistry) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GatewayDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	GatewayName   string                 `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	GatewayDomain string                 `protobuf:"bytes,3,opt,name=gateway_domain,json=gatewayDomain,proto3" json:"gateway_domain,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,4,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayDetails) Reset() {
	*x = GatewayDetails{}
	mi := &file_proto_maps_maps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayDetails) ProtoMessage() {}

func (x *GatewayDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_maps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayDetails.ProtoReflect.Descriptor instead.
func (*GatewayDetails) Descriptor() ([]byte, []int) {
	return file_proto_maps_maps_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayDetails) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayDetails) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *GatewayDetails) GetGatewayDomain() string {
	if x != nil {
		return x.GatewayDomain
	}
	return ""
}

func (x *GatewayDetails) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

type AgentDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName      string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentDomain    string                 `protobuf:"bytes,3,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	Region         string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Port           int64                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	GatewayDetails *GatewayDetails        `protobuf:"bytes,7,opt,name=gateway_details,json=gatewayDetails,proto3" json:"gateway_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentDetails) Reset() {
	*x = AgentDetails{}
	mi := &file_proto_maps_maps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDetails) ProtoMessage() {}

func (x *AgentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_maps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDetails.ProtoReflect.Descriptor instead.
func (*AgentDetails) Descriptor() ([]byte, []int) {
	return file_proto_maps_maps_proto_rawDescGZIP(), []int{3}
}

func (x *AgentDetails) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentDetails) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentDetails) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentDetails) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentDetails) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AgentDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentDetails) GetGatewayDetails() *GatewayDetails {
	if x != nil {
		return x.GatewayDetails
	}
	return nil
}

type GetGatewaybyRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewaybyRegion) Reset() {
	*x = GetGatewaybyRegion{}
	mi := &file_proto_maps_maps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewaybyRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewaybyRegion) ProtoMessage() {}

func (x *GetGatewaybyRegion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maps_maps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewaybyRegion.ProtoReflect.Descriptor instead.
func (*GetGatewaybyRegion) Descriptor() ([]byte, []int) {
	return file_proto_maps_maps_proto_rawDescGZIP(), []int{4}
}

func (x *GetGatewaybyRegion) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_proto_maps_maps_proto protoreflect.FileDescriptor

const file_proto_maps_maps_proto_rawDesc = "" +
	"\n" +
	"\x15proto/maps/maps.proto\x12\amaps.v1\"\xa7\x02\n" +
	"\rAgentRegistry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12!\n" +
	"\fagent_domain\x18\x03 \x01(\tR\vagentDomain\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x03R\x04port\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x10\n" +
	"\x03ttl\x18\a \x01(\x03R\x03ttl\x12%\n" +
	"\x0egateway_domain\x18\b \x01(\tR\rgatewayDomain\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\t \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\n" +
	" \x01(\tR\tgatewayIp\"\xdb\x01\n" +
	"\x0fGatewayRegistry\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12%\n" +
	"\x0egateway_domain\x18\x03 \x01(\tR\rgatewayDomain\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x04 \x01(\tR\tgatewayIp\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x10\n" +
	"\x03ttl\x18\a \x01(\x03R\x03ttl\"\x98\x01\n" +
	"\x0eGatewayDetails\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12%\n" +
	"\x0egateway_domain\x18\x03 \x01(\tR\rgatewayDomain\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x04 \x01(\tR\tgatewayIp\"\xf1\x01\n" +
	"\fAgentDetails\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12!\n" +
	"\fagent_domain\x18\x03 \x01(\tR\vagentDomain\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x03R\x04port\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12@\n" +
	"\x0fgateway_details\x18\a \x01(\v2\x17.maps.v1.GatewayDetailsR\x0egatewayDetails\",\n" +
	"\x12GetGatewaybyRegion\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region2\x90\x01\n" +
	"\x04Maps\x12G\n" +
	"\x0fGatewaybyRegion\x12\x1b.maps.v1.GetGatewaybyRegion\x1a\x17.maps.v1.GatewayDetails\x12?\n" +
	"\rRegisterAgent\x12\x16.maps.v1.AgentRegistry\x1a\x16.maps.v1.AgentRegistryB7Z5github.com/dipghoshraj/ingress-tunnel/registry/proto/b\x06proto3"

var (
	file_proto_maps_maps_proto_rawDescOnce sync.Once
	file_proto_maps_maps_proto_rawDescData []byte
)

func file_proto_maps_maps_proto_rawDescGZIP() []byte {
	file_proto_maps_maps_proto_rawDescOnce.Do(func() {
		file_proto_maps_maps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maps_maps_proto_rawDesc), len(file_proto_maps_maps_proto_rawDesc)))
	})
	return file_proto_maps_maps_proto_rawDescData
}

var file_proto_maps_maps_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_maps_maps_proto_goTypes = []any{
	(*AgentRegistry)(nil),      // 0: maps.v1.AgentRegistry
	(*GatewayRegistry)(nil),    // 1: maps.v1.GatewayRegistry
	(*GatewayDetails)(nil),     // 2: maps.v1.GatewayDetails
	(*AgentDetails)(nil),       // 3: maps.v1.AgentDetails
	(*GetGatewaybyRegion)(nil), // 4: maps.v1.GetGatewaybyRegion
}
var file_proto_maps_maps_proto_depIdxs = []int32{
	2, // 0: maps.v1.AgentDetails.gateway_details:type_name -> maps.v1.GatewayDetails
	4, // 1: maps.v1.Maps.GatewaybyRegion:input_type -> maps.v1.GetGatewaybyRegion
	0, // 2: maps.v1.Maps.RegisterAgent:input_type -> maps.v1.AgentRegistry
	2, // 3: maps.v1.Maps.GatewaybyRegion:output_type -> maps.v1.GatewayDetails
	0, // 4: maps.v1.Maps.RegisterAgent:output_type -> maps.v1.AgentRegistry
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_maps_maps_proto_init() }
func file_proto_maps_maps_proto_init() {
	if File_proto_maps_maps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maps_maps_proto_rawDesc), len(file_proto_maps_maps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_maps_maps_proto_goTypes,
		DependencyIndexes: file_proto_maps_maps_proto_depIdxs,
		MessageInfos:      file_proto_maps_maps_proto_msgTypes,
	}.Build()
	File_proto_maps_maps_proto = out.File
	file_proto_maps_maps_proto_goTypes = nil
	file_proto_maps_maps_proto_depIdxs = nil
}
