syntax = "proto3";


package maps.v1;

option go_package = "github.com/dipghoshraj/ingress-tunnel/registry/proto/";


// protoc --go_out=. --go-grpc_out=../. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative proto/maps/maps.proto
service Maps {
    rpc SetGateway (GatewayPutRequest) returns  (GatewayResponse);
    rpc SetAgents (AgentConnectionRequest) returns (AgentResponse);
    rpc GetRegionalGateway (GatewayHandshak) returns (GatewayResponse);
    rpc GetProxyGateway (GatewayProxy) returns (GatewayResponse);
}


message GatewayPutRequest {
    string region = 1;
    string gateway_ip = 2;
    string gateway_domain = 3;
    int32 gateway_port = 4;
    Capacity capacity = 5;
}

message Capacity {
    int32 cpu = 1;
    int32 memory = 2;
    int32 storage = 3;
    int32 bandwidth = 4;
}

message GatewayResponse {
    string gateway_id = 1;
    string gateway_ip = 2;
    string gateway_domain = 3;
}

message AgentConnectionRequest {
    string domain = 1 ;
    string gateway_id = 2;
    string region = 3;
    string agent_domain = 4;
}

message AgentResponse {
    string agent_id = 1;
    string agent_domain =2;
    string gateway_id=3;
    string gateway_doamin = 4;
    Capacity capacity = 5;
}

message GatewayHandshak {
    string region = 1;
}

message GatewayProxy {
    string agent_domain = 1;
}