// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: proto/maps/maps.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Maps_GatewaybyRegion_FullMethodName = "/maps.v1.Maps/GatewaybyRegion"
	Maps_RegisterAgent_FullMethodName   = "/maps.v1.Maps/RegisterAgent"
)

// MapsClient is the client API for Maps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapsClient interface {
	GatewaybyRegion(ctx context.Context, in *GetGatewaybyRegion, opts ...grpc.CallOption) (*GatewayDetails, error)
	RegisterAgent(ctx context.Context, in *AgentRegistry, opts ...grpc.CallOption) (*AgentRegistry, error)
}

type mapsClient struct {
	cc grpc.ClientConnInterface
}

func NewMapsClient(cc grpc.ClientConnInterface) MapsClient {
	return &mapsClient{cc}
}

func (c *mapsClient) GatewaybyRegion(ctx context.Context, in *GetGatewaybyRegion, opts ...grpc.CallOption) (*GatewayDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayDetails)
	err := c.cc.Invoke(ctx, Maps_GatewaybyRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) RegisterAgent(ctx context.Context, in *AgentRegistry, opts ...grpc.CallOption) (*AgentRegistry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRegistry)
	err := c.cc.Invoke(ctx, Maps_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapsServer is the server API for Maps service.
// All implementations must embed UnimplementedMapsServer
// for forward compatibility.
type MapsServer interface {
	GatewaybyRegion(context.Context, *GetGatewaybyRegion) (*GatewayDetails, error)
	RegisterAgent(context.Context, *AgentRegistry) (*AgentRegistry, error)
	mustEmbedUnimplementedMapsServer()
}

// UnimplementedMapsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapsServer struct{}

func (UnimplementedMapsServer) GatewaybyRegion(context.Context, *GetGatewaybyRegion) (*GatewayDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewaybyRegion not implemented")
}
func (UnimplementedMapsServer) RegisterAgent(context.Context, *AgentRegistry) (*AgentRegistry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedMapsServer) mustEmbedUnimplementedMapsServer() {}
func (UnimplementedMapsServer) testEmbeddedByValue()              {}

// UnsafeMapsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapsServer will
// result in compilation errors.
type UnsafeMapsServer interface {
	mustEmbedUnimplementedMapsServer()
}

func RegisterMapsServer(s grpc.ServiceRegistrar, srv MapsServer) {
	// If the following call pancis, it indicates UnimplementedMapsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maps_ServiceDesc, srv)
}

func _Maps_GatewaybyRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewaybyRegion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GatewaybyRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_GatewaybyRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GatewaybyRegion(ctx, req.(*GetGatewaybyRegion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegistry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).RegisterAgent(ctx, req.(*AgentRegistry))
	}
	return interceptor(ctx, in, info, handler)
}

// Maps_ServiceDesc is the grpc.ServiceDesc for Maps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maps.v1.Maps",
	HandlerType: (*MapsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GatewaybyRegion",
			Handler:    _Maps_GatewaybyRegion_Handler,
		},
		{
			MethodName: "RegisterAgent",
			Handler:    _Maps_RegisterAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/maps/maps.proto",
}
